### ISSUE TITLE
Please decide whether the project is in English or German and be consequent.

### ISSUE THREAD

**Issue by James-Antrim** [thm-mni-ii/thesis-template#1]

**Comment by priefyou** [comment]
@James-Antrim, thank you for your comment. Are you willing to contribute to the project and rename the files and folders appropriately?

**Comment by James-Antrim** [comment]
preambel => preamble
tabellen => tables
vorlage => template
titel => title
einfuehrung => introduction
hintergrund => background/context
konzept => concept
realisierung => realization(us)/realisation(gb)
abschluss => conclusion
longtablebeispiel => longtableexample

**Comment by James-Antrim** [comment]
Or just go German. It's a valid option.
I wasn't trying to be snarky, but mixed languages never look good.

**Comment by priefyou** [comment]
Thank you @James-Antrim. I totally agree :-)
